# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ This file is only read once per server start. Restart server when changed! ║
# ╚════════════════════════════════════════════════════════════════════════════╝

# Site settings
# ─────────────
baseurl: /allpaintworks
# host   : 127.0.0.1
# port   : 4000

# Custom Site variables
# ─────────────────────
title: All Paint Works

# Build settings
# ──────────────


exclude:
  - Gemfile
  - README.md

plugins:
# - jekyll-feed
# - jekyll-gist
# - jekyll-mentions
# - jekyll-paginate
# - jekyll-redirect-from
# - jekyll-seo-tag
# - jekyll-sitemap
# - jemoji

sass:
  style: nested
#  style: expanded
#  style: compact
#  style: compressed

